# Generated by Django 2.2.8 on 2019-12-17 20:44

from django.db import migrations, models
import url_shortener.links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(default=url_shortener.links.models.generate_short_url, max_length=8, unique=True, verbose_name='Shortened url'),
        ),
    ]
