# Generated by Django 2.2.8 on 2019-12-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20191217_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='redirect_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Redirect Count'),
        ),
    ]
