# Generated by Django 2.2.8 on 2019-12-17 22:03
import uuid

from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Link = apps.get_model('links', 'Link')
    for row in Link.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20191217_2158'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
