# Generated by Django 2.2.8 on 2019-12-17 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20191217_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
