# Generated by Django 2.2.8 on 2019-12-19 13:31

import django.core.validators
from django.db import migrations, models
import url_shortener.links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20191217_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='full_url',
            field=models.CharField(max_length=2000, validators=[django.core.validators.RegexValidator(message='Enter a valid url starting with http', regex='^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)$')], verbose_name='Full url'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(default=url_shortener.links.models.generate_short_url, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Enter 4-8 alphanumeric characters', regex='^[a-zA-Z\\d_-]{4,8}$')], verbose_name='Shortened url'),
        ),
    ]
